name: TrainingMaterial_v0.4-DRAFT-2018_11_16
id: http://example.org/example
imports:
- linkml:types
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  schema1:
    prefix_prefix: schema1
    prefix_reference: http://schema.org/
  bioschemas:
    prefix_prefix: bioschemas
    prefix_reference: https://discovery.biothings.io/view/bioschemas/
default_prefix: example
default_range: string
classes:
  CreativeWork:
    name: CreativeWork
    from_schema: http://example.org/example
    class_uri: schema1:CreativeWork
  TrainingMaterial:
    name: TrainingMaterial
    comments:
    - 'A specification for describing training materials in life sciences. The Life
      Science Training Materials specification provides a way to describe bioscience
      training material on the World Wide Web. It defines a set of metadata and vocabularies,
      built on top of existing technologies and standards, that can be used to represent
      events in Web pages and applications. The goal of the specification is to make
      it easier to discover, exchange and integrate life science training material
      information across the Internet. Version: 0.4-DRAFT-2018_11_16'
    from_schema: http://example.org/example
    is_a: CreativeWork
    class_uri: bioschemas:TrainingMaterial
