name: TrainingMaterial_v0.8-DRAFT-2020_10_06
id: http://example.org/example
imports:
- linkml:types
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/
  schema1:
    prefix_prefix: schema1
    prefix_reference: http://schema.org/
  bioschemas:
    prefix_prefix: bioschemas
    prefix_reference: https://discovery.biothings.io/view/bioschemas/
default_prefix: example
default_range: string
classes:
  LearningResource:
    name: LearningResource
    from_schema: http://example.org/example
    class_uri: schema1:LearningResource
  TrainingMaterial:
    name: TrainingMaterial
    comments:
    - 'A specification for describing training materials in life sciences. The Life
      Science Training Materials specification provides a way to describe bioscience
      training material on the World Wide Web. It defines a set of metadata and vocabularies,
      built on top of existing technologies and standards, that can be used to represent
      events in Web pages and applications. The goal of the specification is to make
      it easier to discover, exchange and integrate life science training material
      information across the Internet.<h4>Summary of Changes</h4>    Changes since
      previous draft 0.7 of the TrainingMaterials profile:    <ul>      <li>Changes
      learningOutcomes (non existant property) to teaches</li>      <li>Changes featuredInEvent
      (non existant property) to recordedIn</li>      <li>Removes uses (non existant
      property, used for works used by this TtrainingMaterial) and reuses mentions
      for this purpose(before it was used only for other works referenced by this
      TrainingMaterial</li>      <li>Changes skillLevel (non existant property) to
      educationalLevel</li>      <li>Changes status (non existant property) to creativeWorkStatus</li>      <li>Changes
      tranlastedInto (non existant property) to workTranslation</li>      <li>Changes
      parent type to LearningResource, it was before CreativeWork, LearningResource
      extends it and is more appropriate</li>      <li>Changes prepared by L. Garcia</li>    </ul>
      Version: 0.8-DRAFT-2020_10_06'
    from_schema: http://example.org/example
    is_a: LearningResource
    class_uri: bioschemas:TrainingMaterial
